### ISSUE TITLE
Timer Example

### ISSUE THREAD

**Issue by www-AlphaCentaurus-Net** [Alex079/TinySuite#1]
Hi Alex;

Please. 
Do you have a usage example of TinyTimer0Overflow and/or TinyTimer1Overflow?

Thanks

**Comment by Alex079** [comment]
Hi!
Sorry for replying late, I just saw your message.
I think there might be a bug in prescaler. I'll check.

**Comment by Alex079** [comment]
I added a branch with a fix and an example. I'll need to run more tests to make sure it's ready. https://github.com/Alex079/TinySuite/compare/timer-prescaler
Thank you!

**Comment by Alex079** [comment]
see #2 for details
