### ISSUE TITLE
How to include watchdog code into Arduino sketch?

### ISSUE THREAD

**Issue by Barabba11** [Alex079/TinySuite#6]
Hi, thanks for sharing your library, I can0t figure out how to load watchdof on my Digispark, I don't need sleep mode, I just need a protection (reboot) in case the CPU hangs. Thank you

**Comment by Alex079** [comment]
Hi!
I think the minimal example would be
```C++
#include <avr/interrupt.h>
#include <TinyWatchdog.h>
int main() {
  sei();
  Watchdog.armReset(9, 0);
  // here goes your code, which calls Watchdog.armReset(9, 0) again from time to time
}
```
In this case a reset should be triggered directly without callback (callback value of 0) after about 8 seconds (prescaler value of 9).
I guess you will have to call `Watchdog.armReset` repeatedly in your code to tell the watchdog that your code is still alive.
I have not used this scenario myself yet.

I hope this helps.
Regards

**Comment by Barabba11** [comment]
Hi, thanks for replying! Sorry if I ask stupid questions, 
what is int main? is it a routine for interrupt? is it conteined on TinyWatchdog.h or avr/interrupt.h?
I don't get how to write this on a Arduino sketch, can you please help me there? 

Should it be like:
```
#include <avr/interrupt.h>
#include <TinyWatchdog.h>
void setup() {
int main() {
  sei();
  Watchdog.armReset(9, 0);}
}

void loop() {
Watchdog.armReset(9, 0);
}
```

Thank you!

**Comment by Barabba11** [comment]
I have an exit status 1 on Arduino IDE, can't compile (

**Comment by Alex079** [comment]
Right, sorry. Arduino sketch would look like this
```C++
#include <TinyWatchdog.h>

void setup() {
  // setup code goes here
}

void loop() {
  // some code may go here
  Watchdog.armReset(9, 0);
  // more code may go here
}
```

**Comment by Barabba11** [comment]
Errore durante la compilazione per la scheda ATtiny85 (Micronucleus / DigiSpark).
Errore durante la compilazione per la scheda Digispark (Default - 16.5mhz).

Thank you, unfortunately the compiler refuses to work, I've tried with 2 different board's libraries

**Comment by Alex079** [comment]
OK, interesting. With this bootloader selected, the error is gone when I disable millis/micros in tools (v1.8.15). Does it work for you?

**Comment by Barabba11** [comment]
Can you please explain me how can I disable it? tools (v1.8.15) is a software? Can I change with that the parameters (fuses) inside ATtiny85? Can I also update the Bootloader? 
I don't have programmer, just USB..
Thank you

**Comment by Alex079** [comment]
I mean this
![Screenshot from 2022-07-26 22-28-24](https://user-images.githubusercontent.com/21042652/181106307-45679b54-0701-4f5e-8875-27e1a45b8e11.png)

**Comment by Barabba11** [comment]
Man, I've realized how to update the BL of Digispark and I succeed, it's easy and via USB, I strongly recomend everybody to do it. Now Watchdog can work good like it does on arduino with avr/wdt.h.. 
I've lost half day for such issue :/
Thank you for your kind help
